services:

  edge:
    image: private-billing
    ports:
      - 5555:5555
    environment:
      - SERVER_TYPE=edge
      - EDGE_HOST=edge
      - EDGE_PORT=5555
    networks:
      - billing

  core0:
    image: private-billing
    ports:
      - 5560:5560
    environment:
      - SERVER_TYPE=core
      - EDGE_HOST=edge
      - EDGE_PORT=5555
      - CORE_HOST=core0
      - CORE_PORT=5560
    networks:
      - billing

  core1:
    image: private-billing
    ports:
      - 5561:5561
    environment:
      - SERVER_TYPE=core
      - EDGE_HOST=edge
      - EDGE_PORT=5555
      - CORE_HOST=core1
      - CORE_PORT=5561
    networks:
      - billing

  core2:
    image: private-billing
    ports:
      - 5562:5562
    environment:
      - SERVER_TYPE=core
      - EDGE_HOST=edge
      - EDGE_PORT=5555
      - CORE_HOST=core2
      - CORE_PORT=5562
    networks:
      - billing
  
  core3:
    image: private-billing
    ports:
      - 5563:5563
    environment:
      - SERVER_TYPE=core
      - EDGE_HOST=edge
      - EDGE_PORT=5555
      - CORE_HOST=core3
      - CORE_PORT=5563
    networks:
      - billing

  core4:
    image: private-billing
    ports:
      - 5564:5564
    environment:
      - SERVER_TYPE=core
      - EDGE_HOST=edge
      - EDGE_PORT=5555
      - CORE_HOST=core4
      - CORE_PORT=5564
    networks:
      - billing

networks:
  billing:
    name: "billing"
    driver: bridge